---
  version: '3.5'
  services:
      db:
        image: mariadb:latest
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
          - db:/var/lib/mysql
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_USER: nextcloud
          MYSQL_DATABASE: nextcloud
          MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
  
      nextcloud:
        image: nextcloud:18-apache
        depends_on:
          - db
        ports:
          - 3000:80
        volumes:
          - ./www:/var/www/html
  
  volumes:
    db: